### PR TITLE
Tutorial

### PR DESCRIPTION
**Pull request by carlsuarez**
This PR introduces two new additions:

1. Tutorial
- A tutorial system has been implemented, starting when a player begins a new game.
- The tutorial progresses based on specific player actions. Dialogue segments are stored in a JSON file, and the next segment plays when the player performs certain actions (e.g., placing a power plant or entering the store).
- Currently the story is not complete but the tutorial system is

2. Tide Sensor Lab Scene
- A lab scene currently plays a tutorial scene when the player clicks "more information" on a tide sensor.
- This scene is displayed only once and provides brief information about the tide sensor.

Please test and share any feedback or issues you encounter!

### CODE REVIEW

**Comment by devp4** [comment]
Everything works with no bugs on my end!

Some small thoughts :
- It says power plant in the tutorial, but the building is called utility plant. maybe keeping them the same to avoid confusion?
- On the second segment, it says to "place a building and road" but maybe it should specify house and shop (cause if they place other buildings they will run out of money)
- When i click more info on the tide sensor, a background changes but nothing happens on it. is that expected?

Other than that, everything looks good!

**Comment by carlsuarez** [comment]
Thanks for the input, Dev. I added the dialogue changes you recommended. Regarding the lab background appearing with nothing happening, there is a tutorial scene there, but it will only show up after you buy the tide sensor and close the popup that comes after purchasing.

**Review by rafaela-eacf — CHANGES_REQUESTED** [review]
Looks very cool! I like how the tutorial is more of an optional helper instead of being mandatory for the player. There's just one issue I noticed when I pressed the "ask for help" button when I was placing the tide sensor. It threw an error saying "Invalid call. Nonexistent function 'setCharacter' in base CanvasLayer(Tutorial.Gd)". Do you know what could be causing it?

**Comment by carlsuarez** [comment]
Thank you for the input! I just pushed a commit to fix the bug. It was some old code that tried to instantiate the tutorial when you pressed "ask for help". I changed it back to the old code that the other sensors use.

**Review by emenello — CHANGES_REQUESTED** [review]
Hi CJ! It all looks really good, I'm happy to see the tutorial finally get a push to main. There is one small bug I noticed. When the player is prompted to enter their name at the beginning, if you press ENTER, the name is updated as intended. However, if the user presses the Start button manually, it does not update the name and keeps it as noName. I don't know if this is just on my end but other than that looks great!

**Comment by carlsuarez** [comment]
Good catch! The issue was that the wrong signal was used to set Global.userName in userName.gd.

**Review by rafaela-eacf — APPROVED** [review]

**Review by devp4 — APPROVED** [review]

**Review by emenello — APPROVED** [review]

**Pull request merged**
