### PR TITLE
Zoning Changes

### PR DESCRIPTION
**Pull request by acher0nparth**
## Summary of Changes
- Light and Heavy Commercial zoning has been replaced by a single Commercial zone
- Light Residential zones are now Single Family zones
- Heavy Residential zones are now Multi Family zones
- Single Family zones have a population limit of 4 people, down from 16
- Multi Family zones have a population limit of 72 people, up from 16
    - This has resulted in the buildings becoming VERY tall when full, blocking out other tiles. This will be resolved when we shift to        the new asset pack, hopefully.
-  Refactored some of the code related to tracking the number of zones of each type, so it should be more streamlined and intuitive now. Numbers of Residential, Single Family, Multi Family, and Commercial zones can be gotten from `City.gd`.
- Single Family and Multi Family zones now have individual upkeep costs. They should probably be adjusted for balance, but this can easily be done by adjusting constants in `Econ.gd`.
- Added upkeep costs for each person in the city, representing the wear and tear that each additional person causes on roads, infrastructure, etc. This may also be adjusted via a constant in `Econ.gd`

## Notes
The new population numbers may seem quite different than previous, because they are. I conceive of our population numbers as 100 times less than the number they actually represent. So, a single family zone can actually hold 400 people, and we abstract that down to 4 to make it easier to think about as a player. The same is true for multi family: 7200 people in a given zone, reduced to 72. These numbers are in-line with the figures Patriel provided in the Teams. 

## Areas of Improvement/Feedback Wanted
- I don't think that the multi family zoning has a large enough cost to ever justify choosing single family over multi family, since it can fit so many more people. Please play around with this PR and let me know if you agree, and I can make the costs higher to make single family zoning a viable choice. 
- I tried to update the graphics to fill in properly, and I think it works, but I'm not 100%. Let me know if you see any graphical anomalies, like buildings remaining grey when they should be green. 
- It currently costs nothing to lay down a given zone type, which makes sense from a political perspective since zoning is free. We can avoid incurring a cost by saying a developer is the one building on a given zone, not us, so it shouldn't cost us anything to lay down a zone or get a larger building. I'm not sure how I feel about this, but it might be offset with larger upkeep costs associated with each zone type. Basically, I'm worried that the player will never have any issues generating income as long as they have positive population growth, which may or may not be desired. Let me know what you all think. 

As always, please try your best to break it! Thanks.

### CODE REVIEW

**Review by rafaela-eacf — APPROVED** [review]
Code definitely looks cleaner and easier to follow. I couldn't find any bugs, but I agree that there is no advantage in picking single family housing over multi right now.

**Comment by Lchenicek** [comment]
image
Hey Blake, I like the changes to the code and it all looks good, but I was able to find one bug. If I make a city above with only multi homes, it works, but once I add a commercial zone, I get an exception saying Invalid get 'numCommercialZones' on base global. It looks to me like it's because of line 167 which should I think be City.numCommercialZones instead of Global.numCommercialZones. Hope that helps!
image

**Review by lolxela — CHANGES_REQUESTED** [review]
I got the same issue as Logan after adding more than 2 commercial zones which breaks the game for me. I also agree about possibly raising the price of multi family households or finding another way to necessitate single family.

**Comment by acher0nparth** [comment]
I think I have successfully fixed the bug, it was right where Logan said it was! Thanks again. I have also upped the base desirability for single family zones to double its previous value. This makes the tile values for single family zones a fair bit higher than for multi family. This definitely doesn't fix the issue since multi family zones still generate way more revenue because more people. I'm thinking the best place to address this will be in the population agent code that we work on next semester; the agent could prefer to live in a single family zone, for example, so multi family zones don't fill up as fast.

**Review by Lchenicek — APPROVED** [review]
Game no longer crashes and all changes look great. Nice work!

**Review by emenello — APPROVED** [review]
The bug is fixed! Awesome job Blake everything looks great!

**Review by lolxela — APPROVED** [review]
Looks good!

**Pull request merged**
