### PR TITLE
Beach + Weather

### PR DESCRIPTION
**Pull request by rafaela-eacf**
Hey guys! This is a combined PR between Logan and I. Here are our main changes:
Beach Changes:
- Modified the JSON for the default map so the user has more beach tiles to work with.
- Boardwalks, houses, multifamily housing, and shops can all be placed on the beach. Boardwalks are essentially the roads of the beach.
- House’s and shop’s desirability are increased on beaches.
- Beach grass and beach rocks lower the desirability of surrounding tiles. You can remove these for 3,000.
- You can close the beach down by pressing the close beach button. This feature will be expounded upon in the future. Right now, how it should work is that when you press the button, next week, people will start leaving throughout the week. Then they stay evacuated for a week and finally move back during the next week. This was tied to storms at first, and will be eventually, but that will be done once we have warning systems finished.
- The sensor section of the toolbar only appears when you have a sensor in your inventory. The buttons will be removed or added as needed.

Weather changes:
- Tide sensor is connected to sea level. If placed on an ocean base, it will read the current sea level and allow data storage. 
- Rain sensor is connected to rain level. If placed on a dirt base, it will read the current rain level and allow data storage.
- Wind sensor is connected to wind level. If placed on a sand base, it will read the current wind level and allow data storage.
- Each sensor type can only be bought once. Right clicking on a tile that contains a sensor will clear the tile and return the sensor to inventory. 
- Sensors can be placed on top of buildings, as long as the buildings are drawn with the new assets. That means that sensors cannot be placed on top of beach rocks/grass; sensors cannot be placed on a zoned building if the building has not been built yet; and sensors cannot be placed on top of fire stations (weird bug that does not allow sensor to be visible if you place it in one of its other three tiles that it occupies so I just don't allow sensor placement there).
- Storms can happen in the months of June-November. The chances of a storm happening are very low so to test this you guys will have to let the game run for a little bit or just change the date_ticks inside updateDate to 10 for every instance change to see storms happening more frequently (makes testing faster). 
- Storm surges can happen if the player removes enough beach rocks. Try playing with that feature! Remove some beach rocks/grass and when a storm appear there is a chance that it will come with a storm surge. Adding wave breakers decreases that chance.  

Please let us know if something is not working or if you want to suggest improvements to any of our systems!

### CODE REVIEW

**Comment by lolxela** [comment]
I love this PR, really good work!! 

Some things I noticed when reviewing:
It looks like you can still remove beach rocks and grass by right clicking on them without it costing any money. 
(Nits) I know you mentioned removing a sensor will clear the tile, but I feel like maybe the buildings should remain when a sensor is removed from them.
Maybe when the close beach button is pressed, the button should be grayed out until the following week. You can click another tool and then reselect it but it won't have an affect if its within the same week it looks like.

**Review by acher0nparth — COMMENTED** [review]
I like the addition of a week counter for each month, it makes understanding the passage of time a little easier for sure. 

I second all of Alex's notes from her review, especially about a visual indicator for the beach being closed. Even a little flag asset or something could be good to add, just so the player knows when it's open or not. I also had the same issue with being able to remove beach rocks for free with a right click, regardless of the selected tool. 

I am having some issues with placing tiles on the beach. Specifically, it's tiles that have a height less than the standard tile height. Is it intentional that we cannot place zones or buildings on them? Also, is it intentional that wave breakers can only be placed within 2 blocks of the ocean? 

I think the wave breakers are a little expensive and maybe should be draggable for placement. This could be my own ignorance about the subject, but it seems like the most intuitive use for them is to put them in a continuous line across the beach, which is difficult in terms of clicks and very expensive in the current setup. If that isn't how they're supposed to be used, maybe some dialogue about it should be added in the future to teach the player how to use them.  

I got a bunch of messages like this in my console while playing: `2629338 - Stray Node:  (Type: Node, Script: res://scripts/Event.gd)`. Seems like some nodes are getting removed from the scene tree and not deleted, probably after an event happens and is processed. It wasn't throwing an error, but I think it should still be looked at. 

I'm not sure why, but when I click the "dashboard" button, nothing happens. I thought the dashboard had been added to main already? I might be misremembering though.

Does the road damage from #16 apply to boardwalks also? I didn't notice any of them getting damaged like a road would. 

I noticed a strange bug with counting commercial areas. I repeatedly put out less than 10 commercial areas but still got the achievement for building 10 commercial zones. 

Do storm surges have a negative impact currently? I set the storm probability to 90% and let the game run for a while with all beach rocks and such removed, but didn't see any damage to the city or boardwalk areas at all regardless of the strength of the storm. I also didn't see any visual indicator of a storm surge so I'm not sure if I got one to trigger, so that could be it.

**Comment by lolxela** [comment]
Disregard this comment, still had the issue opening the dashboard today. ~~I had the same issue with trying to open dashboard but my branch wasn’t up to date even though it said it was. I had to open the branch on GitHub desktop from the PR tab instead of the branches tab and that updated it somehow. Then the dashboard and road damage worked fine for me~~

**Comment by lolxela** [comment]
Oh sorry I misread about the road damage part. For boardwalk damage I asked Rafaela today if she wanted me to add that to this PR, haven’t heard back yet

**Comment by lolxela** [comment]
Added damage to boardwalk and fixed the dashboard bug!

**Review by emenello — APPROVED** [review]
Sorry this review is so late! Everything worked perfectly on my end when I pulled the branch. I think the boardwalk is a super cool new feature and the weather changes make the game closer to what the end goal is. Awesome work!

**Review by devp4 — APPROVED** [review]
Everything ran on my end with no issues! The only thing is what Blake mentioned about not being able to place houses/shops on after the 3rd beach tile. Boardwalks can still be placed there. 

I think like Alex and Blake mentioned, having some indictor (maybe text on bottom right) saying if beach is closed or open. A popup when you click on screen when selecting close beach button could also help. maybe saying "are you sure you want to close the beach" or similar. 

Nice job!

**Pull request merged**
