### PR TITLE
Desirability, Tile Value, and Profit Rates

### PR DESCRIPTION
**Pull request by acher0nparth**
This is a pretty big PR, I touched a lot of files and a lot of the economy functionality. For the player, not much is actually different, but things are much different behind the scenes. As always, try to break it if you can! 

## Refactoring
- I removed redundant and unused code where I could find it
- I renamed `economy_ai.tscn` to `desirability.tscn` because that is more accurate to what it is doing 
- I renamed all instances of 'Power Plant' to 'Utility Plant' and the other forms as dictated by grammar

## Desirability
- Complete overhaul of how desirability is calculated. See `validator.gd` for details, I left in-code comments. 
- I changed the behavior of many of the nodes in `desirability.tscn`, including `city_wealth.gd`, `number_of_zones.gd`, `taxation_rate.gd`, `validator.gd`, `zone_connections.gd`, and `tile_damage.gd`.
- `presence_of_water.gd` is now an unused node. Further optimizations of the water neighbors calculations may reuse that node, so I left it empty. Also, the game doesn't run if you delete it without modifications, so its easier to just leave it. 

## Economy
- Each tile now has a `profitRate` value that is calculated in `Econ.gd`. It represents how much revenue a certain tile brings the city. 
- City income is now a function of these profit rates. 
- Profit rates are now used in the desirability calculations, linking the previously unlinked economy systems. 
- I have redone the implementation of taxes: there are now Sales, Income, and Property taxes. Sales and Property taxes define the profit of commercial tiles, and Income and Property taxes define the profit of residential tiles. Rates are adjustable in-code, not by the player as of yet. 
- Tile Value is now a function of desirability, which further links the two systems. So, by increasing the desirability of a tile, you increase its value, which increases its profit rate, which affects its desirability, and so on. This is not a fully circular system since it doesn't endlessly raise the value of a tile, but I feel that it more closely emulates an actual economy than the previous system. It also means that city income can be reduced or increased by removing or adding parks, for example, which increase the desirability of a tile and therefore its value and profit. 
- The city income display now updates weekly instead of every game tick. The profit rates and such are more volatile now, so I reduced the reporting speed to make it more user-friendly. The profit only occurs once a month anyway, so it's more for visual benefit to the player than anything else. 
- I set the starting cash to 20k in `default.json`. 

## Happiness
- I added a high unemployment penalty to the happiness calculations. If unemployment is above 10%, happiness gets a large penalty. It doesn't actually affect much of anything as it stands currently, but I felt it was a good addition. Revisions to this will come with the AI Agent stuff.

### CODE REVIEW

**Review by Lchenicek — APPROVED** [review]
I was not able to find any bugs in the PR, really great work. These changes make the game a lot more fun too! Feels like the player actually has to worry about making a profitable city now.

**Review by emenello — APPROVED** [review]
Everything worked for me, I couldn't find any bugs when I was playing around with it. Awesome job on this Blake, the economy definitely seems to make a lot more sense and as a player you get a lot more incentive to play the game! Much more fun and the game flows a lot better.

**Review by lolxela — APPROVED** [review]
Very intuitive! Couldn’t break anything

**Review by rafaela-eacf — APPROVED** [review]
Looks good! I couldn't find any bugs either.

**Pull request merged**
