### PR TITLE
UI

### PR DESCRIPTION
**Pull request by Lchenicek**
Mainly an overhaul of the UI, new layout of top bar for easier access to other menus and information on money, population and other yet to be implemented information. Toolbar is now scrollable and is instantiated via code so it is easier to add/remove buttons. Easier to edit too since they're all based on the same scene. Also included adding the inventory system, and added public service/emergency service buildings. All of these buildings must be powered to give desirability buff now.

Notes:
- Worked with Rafaela on sensors so some earlier commits deal with sensors and the shop. They were removed before the PR of this branch to make this PR solely about the UI changes but will be easily added back when Rafaela PR's the Sensor branch.
- Merged Blake's Zoning branch into this one already so that there should be no merged conflicts once that one is on main.

### CODE REVIEW

**Review by emenello — APPROVED** [review]
The new UI looks great! I love how the player can see how many of a certain item they have, and I think it's a lot easier to navigate if you don't know what buttons do previously!

**Review by rafaela-eacf — APPROVED** [review]

**Review by acher0nparth — CHANGES_REQUESTED** [review]
I noticed some inconsistencies when items are getting purchased. When I start up the city and buy a power plant and some roads, the only thing that is getting deducted from the player's money is upkeep costs, not the 10 grand for the power plant and whatever the roads cost. Placing a second utility plant _does_ subtract the 10k though, so that's kind of weird. This issue does not apply to waste or sewage facilities. Looking at it more in-depth, I wonder if the little number badges mean the player starts with a certain number of structures for free (1 utility plant, 10 roads, and 2 parks)? That would explain the behavior. I don't recall a discussion of starting with free buildings which is probably why I'm confused. 

There is also a button to add water, but there currently is no way to remove water (e.g., fill in a canal). It also doesn't cost anything to add water, and I know Patriel had mentioned wanting that to cost a lot of money. 

All the new buildings seem to work as well. I like the inventory management system, seems good. I can't wait until we get the asset pack loaded in; I think the game will really start to pop with the variety of buildings we now have to place. I don't see any real issues other than the two I noted above. The first one might not even need to be changed, and the second one might be a little out of scope, so if that's the case let me know and I'll switch my review to approved. Good work!

**Comment by Lchenicek** [comment]
Hey Blake,

Sorry for the late response. Yes, you're correct about the free utility plant and roads. We did discuss having some sort of inventory system because it's helpful for the sensor system that Rafaela developed. But you are right that we never discussed which, if any, buildings would be given to the user, so I have removed them for now. It'll be used for the sensors and exists for other buildings if we want them in the tutorial, for example.

I also added a cost to adding water, I just set it to $5,000 for now. This is easily changeable so we can discuss with Patriel in our next meeting how much it should cost. At least in the figma board I was sent, I never saw a button for adding land, but I would agree that that's helpful to have. I feel like we should ask Patriel about this too as I'm unsure of whether or not it should just raise to be around the height of adjacent tiles or if we should give the player access to raise/lower a tile to the desired height.

Let me know if there's anything else!

**Comment by lr2120** [comment]
The new layout looks great, especially the icons and scrolling. However, I've noticed that some icons cannot be placed on tiles, including sewage facility and utility plant (which are 3D models). The water tiles are impressive with their depth effect when selected, but the road, bridge, and icons in emergency services and public services categories don't appear responsive.

**Review by lr2120 — APPROVED** [review]
Does not cause functionality issues. Please see my earlier comments on the inability to put some of the tiles on the board.

**Review by acher0nparth — CHANGES_REQUESTED** [review]
Looks like you fixed my changes from last time, really great. I have some very quick notes: 
- the hover text on all buttons is "Road/Power Tile", which I assume is not right.
- I think a popup when someone tries to place something they don't have the money for might be a good idea. That doesn't need to be implemented here, just a general suggestion for a future UI-related PR. 
- it seems like schools, libraries, museums, and parks may be able to overwrite one another. I'm not sure if this extends to other categories, but I think the standard behavior is not to be able to overwrite anything with anything else without making a right-click to clear.
- I was not able to replicate Liliana's comment. When I have the correct amount of money (which is 10k, although that isn't actually indicated anywhere I think?) I am able to place any tile I tried. Bears more testing but I personally didn't see the issue. 

Pretty much the only things I think need to be fixed are the hover text and the building overwrite, which should be fairly simple to do.

**Comment by Lchenicek** [comment]
Hey Blake and Lilian,

- The hover text is a good catch, completely forgot about that. I set them to each have their own now, most of them are just the name of the tile but if you think any others should be changed to something more specific let me know!
- So the tiles overwriting other tiles thing happens for all tiles right now, and that's been the behavior on main. But I agree that that doesn't seem right so I went ahead and fixed it for all tiles since it wasn't too bad.
- I also added an in-game notification if you don't have enough money using the popup system. Since the popup system uses a queue, I made it only add one error message to the queue at a time since we don't want it filled with error messages.
- About the issues with placing tiles, first make sure you're placing tiles on the green dirt tiles, placing them on sand doesn't work. If you are placing them there and it still doesn't work, can you please send a short video? Or we can meet so I can see the problem because I'm unable to recreate that as well.

Thanks for all your suggestion! Very last minute so I totally don't expect you to be able to read this or review it before our meeting today. But let me know if there's anything else I should change!

**Review by lolxela — APPROVED** [review]
I like it! I'm not seeing any issues. I could have sworn the other day I was placing duplicate tiles (i.e. house) on the same tile and it continued to charge money for them, but maybe that was a different branch. Regardless I wasn't able to replicate it this time.

**Review by devp4 — APPROVED** [review]
Looks great! I didn't run into an issues when testing.

**Review by acher0nparth — APPROVED** [review]
Looks good to me. Full disclosure, I am not able to run the game right now because I'm away from home for a bit, but I read through the code and it seems fine. Alex and Dev say it doesn't break for them, so with that I'm confident enough to approve.

**Pull request merged**
