### PR TITLE
Packaging and Exporting

### PR DESCRIPTION
**Pull request by acher0nparth**
This PR should not in any way affect the actual gameplay of SimCoast. It is centered around making sure the game will run properly when it is exported to EXE format.

**How to test this PR**
As part of testing, I need everyone to do 2 things. However, these tests are only possible on a windows machine, so if you don't have one of those then I think you can just ignore it for now. 
1. Follow the exporting instructions in the wiki (link on sidebar) to create your own EXE and see if it runs. Make sure to do this on the Packaging branch. 
2. Extract the zip file I sent in _#developers_ in the Teams and see if that EXE works for you. It should work the same as the game you exported yourself in step 1.

### CODE REVIEW

**Review by devp4 — APPROVED** [review]
Both parts worked for me!

**Review by Lchenicek — APPROVED** [review]
The game seems fine to me, nothing seems broken in game and it worked when I followed the export steps. Although when I exported it, the map does disappear so I'm wondering if I messed something up or if that happens for you too right now? Anyways, the actual functionality of the code is fine so I'll approve!

**Comment by acher0nparth** [comment]
> The game seems fine to me, nothing seems broken in game and it worked when I followed the export steps. Although when I exported it, the map does disappear so I'm wondering if I messed something up or if that happens for you too right now? Anyways, the actual functionality of the code is fine so I'll approve!

@Lchenicek that should not be happening, and does not happen to me. The easiest fix I can think of is having the wrong directory structure, did you have a "saves" folder with "default.json", and was the folder at the same directory level as the exe? That would make the map go away for sure but the game would also run

**Comment by Lchenicek** [comment]
Oh yup you're totally right. I somehow missed the last couple steps of making the saves folder. I figured it was user error lol. It's all working perfect now!

**Review by lolxela — APPROVED** [review]
I have a Mac so I will be skipping for now

**Review by emenello — APPROVED** [review]
The game works perfectly for me when I export it and when I unzip the folder you sent! Super exciting!

**Review by rafaela-eacf — APPROVED** [review]
It worked for me. Very exciting!

**Pull request merged**
