### PR TITLE
New assets

### PR DESCRIPTION
**Pull request by Lchenicek**
Hello everyone, there's a good few changes in here so I'll try to be brief:

- Tiles are now loaded in from PNGs rather than being drawn at runtime. Feel free to update them if you'd like! They're in the assets/building_assets/2d Assets.
- One tile can be spanned across multiple tiles. We haven't exactly figured out what exactly the dimensions should be so for now, the fire station is 2x2 just as an example but the rest are unchanged. This can be modified in the Toolbar script
- There is now a tile placement preview. When you try and place some infrastructure, you now see a preview of the tile you're going to place.
- You can now drag to place and drag to remove tiles that will be placed multiple time. The tiles like this are roads, bridges, water and zones. The rest behave as above.

I think that's most of the changed, let me know if you've found anything. I already merged Alexandria's PR into my branch so I'll wait for that to be merged before merging mine.

### CODE REVIEW

**Review by acher0nparth — CHANGES_REQUESTED** [review]
Long comments incoming, fair warning and I'm sorry in advance lol

I LOVE the preview thing, very awesome. Adds a sense of polish and makes me a little more thoughtful about where I put stuff.  I also really like the assets themselves, the museum is a particular favorite of mine with the columns. 

I was doing some stress testing for my tasks, and as part of that I ran Godot through the command prompt so I could get more verbose error messages. There are some other errors that are present on the other branches (namely some stuff about "mouse_entered/exited"), but there is one on this branch I haven't seen before. The one about not being able to remove the child node, pic below. 
image
I'm not really sure what that is or why it's there, but it is recurring so you should probably try and take a look. It seems to happen when I click buttons on the toolbar, particularly for infrastructure assets like fire stations, libraries, etc. Not really for zoning. May be related to the preview functionality?

Also, the apartments DEFINITELY need some kind of height cap on them. They get outrageously tall , even to the point of getting cut off the screen. Even if you can't fix the node thingy this is for sure necessary before this can get merged. Pic also attached. 
image

The fire station also behaves very strangely when I place it, it's almost like it has a lag or something. The other ones behave fine as far as I can tell. 

Another point of note is that this branch SPIKES our memory usage. I was doing some stuff earlier and the game was hovering around 2-300 megabytes of memory on a branch using the previous assets. My test right now has the game currently at 3.65 _gigabytes_ of memory, and that's climbing rapidly. It is now at 3.8 as I watch it in real time, even though I'm not doing anything to the game and just letting it run. This is, I think, pretty untenable and will overload lower performance computers. Update a few minutes later while I worked on other comments for this: We are now over 5 gigabytes of memory. Wild! This did at least help me clear up an issue that I was having, since I assumed the crashes were caused by extreme memory overload. Clearly not, since the game keeps running fine way over the limits I previously had seen. 

There is also a bug with the preview thing. If I click an asset that has a preview and drag it around without actually placing it, and then go back to the toolbar to click on something that doesn't have a preview like an apartment, the preview for the previous thing will still be hanging out onscreen near the edge where my mouse left the tilemap.

**Comment by Lchenicek** [comment]
Hey @acher0nparth,

I fixed that error message. I had some code that handled removing the preview when we switch to a different tile placement but it wasn't updated for some later changes so I got that all working now.

We discussed capping the apartment heights in last week's meeting so I was going to just do it in my next PR but I guess it makes more sense in this one so I added it here. Each apartment can have up to 4 floor of 16 people.

So for the firehouse lag, so what I think is happening is I've structured it so that the preview displays the last valid position that the tile was in. So if you go from a valid possible position, to a couple of invalid ones, to a valid one, I guess it can look like the tile lags there. The other way I tried invalid previews is I let it display but it was highlighted red. The only issue is that it looked awkward with the overlap with other buildings. Like I either had it look like a weird two story firehouse or it was weirdly under the other. Let me know if you think we should make some changes on this.

Finally, that memory issue is a real good catch. I'm not going to re-request a review quite yet because I'm going to spend some time looking at that and seeing if this is some sort of bug or if I need to make optimizations. I'd guess this is some sort of bug that I overlooked just because of the sheer size, but I'll do some digging. I just wanted to ask how you're testing memory usage? Are you just using task manager?

Thanks as always!

**Comment by Lchenicek** [comment]
Oh and I also forgot to mention, the thing that was causing that error was the code that was supposed to be fixing that last bug you mentioned so fixing the error fixed that as well.

**Comment by acher0nparth** [comment]
I’m using Task Manager, yeah. I think there’s a way to do it in Godot itself and see more specifics than just “amount of memory”, but I’m not super familiar with it.

Blake Thacker
________________________________

**Comment by Lchenicek** [comment]
Thanks! I was easily able to see what you were talking about on Task Manager. I've also learned how to get a breakdown in godot if you're ever curious. I also fixed the memory issue it looks like. I did some digging and the remove_child function doesn't actually seem to delete assets like I thought they would, I have to use queue_free. I'm actually going to bring this up in today's meeting because it looks like we're using this in some other places as well. I also found a new bug with dragging to remove tiles so I'm going to try and fix that before I re-request a review but please test the memory fix whenever you can.

**Comment by Lchenicek** [comment]
Alright @acher0nparth, I think I've fixed all the mentioned bugs now, let me know if there's anything else!

**Review by acher0nparth — CHANGES_REQUESTED** [review]
Looks like you fixed the memory issue, awesome! It's staying well within the realm that we were in previously, and maybe even a little better :) 

I see what you mean now about the firehouse lag being caused by invalid positioning. When I was more careful with my mouse movements I replicated the behavior you mentioned. I do like the idea of making it clear to the user that something is wrong when they try to place a building in an invalid spot, and since it's invalid maybe the looking awkward is fine since its a wrong placement anyway. It's your feature so I'll leave it up to you, it definitely works as intended right now which is great. 

The height cap on the apartments is also great, makes the city look a lot better. I do wish we had some way to change the perspective. The apartments do block out the infrastructure that's behind them, which is unfortunate but also unavoidable due to our fixed perspective. I wonder if changing the camera angle is even possible with our current 2-D setup? Food for later discussion. 

The preview issue I mentioned with the ghost staying there is fixed, good job. 

I did find another bug with the toolbar. I was testing out your drag-to-place functionality, which works great for roads, bridges, water, and zones. However, for any other infrastructure (e.g., utility plant, fire station, park, etc) once I place one of the item the toolbar deselects the option, so if I want to place multiple at a time I have to go click the button each time for it. This isn't such a problem for something expensive like utility plants, but I first noticed it when I tried to place a string of parks down in a row. I'm not sure if this behavior is intended, but IMO it should be fixed so that the toolbar keeps the same option selected until that option gets pressed again (then there is no tool chosen) or another option gets picked. 

Other than that bug, I think everything is in order. Did I mention I love the park asset? The little bench is just perfect. Great job on this PR. Once the toolbar thing is resolved (or you say it was intentional and we move on) I'll be happy to approve.

**Comment by Lchenicek** [comment]
It is intentional that the buildings deselect once you place them. I mentioned this in one of our past two meetings with Patriel and she was fine with it working this way. The thought process is that when the user is placing Zones, Roads, etc, they're going to be placing a lot of them at once. However, the user is typically going to only place one of the other types of infrastructure at a time as they probably don't need too many Fire Stations. Both ways make sense to me though. If you're really passionate about it working the other way, lmk. And we can always discuss this in our weekly meetings. I'm glad you're liking the assets too!

**Review by devp4 — APPROVED** [review]
The preview feature is awesome! I also let the game run for about 30 min and didn't have any memory spikes after the changes. 

image

The apartment height just _barely_ leaves the top of the screen when on the first tile. Could possibly shift the map down a little as there is space. Doesn't cause any issues though, just wanted to mention. 

Other than that, no other bugs on my end!

**Review by acher0nparth — APPROVED** [review]

**Review by rafaela-eacf — APPROVED** [review]
Looks great! I couldn't find any bugs. The only minor thing I noticed was the fire station positioning, like Blake mentioned. If the fire station is surrounded by roads/buildings, it won't move to invalid spots, but I am only able to place it when I select the lower tile. Maybe there is a way to rotate the firehouse to whichever title the player clicks, so that it stays in that square? Here's an image of what I mean. I can only place the fire station when I click on the green tile, but the fire station is still visible when I hover  over the other three tiles, I just can't place it when I click on them. Anyways, not a big deal if you don't fix it, since it is barely an issue. 
Screenshot 2024-03-21 154853

**Review by lolxela — APPROVED** [review]
Looks awesome!! I didn't run into any issues myself

**Review by 0657480051 — APPROVED** [review]

**Review by emenello — APPROVED** [review]
Hey Logan, the new assets look awesome! Definitely makes the game feel more interactive and fun!

**Pull request merged**
