### PR TITLE
Default buildings

### PR DESCRIPTION
**Pull request by devp4**
Small PR

Just adds the 2 buildings to the default map

Things to check:
Make sure original game features work

### CODE REVIEW

**Review by emenello — CHANGES_REQUESTED** [review]
Hi Dev! This looks good and seems like all of the functionality of the game is working. However, when I play the game there seems to be this weird bouncing of the screen almost like it's twitching up and down. I don't know if this is because of how the assets are drawn on the screen but let me know if you can recreate it on your end!

**Review by rafaela-eacf — APPROVED** [review]
Hey Dev! The PR looks very nice. I like the addition of the research center and the town hall. I couldn't find any bugs, but I wonder how this preset will work with the tutorial system that we currently have. Before updating from main and merging, once everyone approves this can you make sure the tutorial will still work properly, or remove some dialogue from the tutorial to make it work? Thanks

**Review by carlsuarez — APPROVED** [review]
Lgtm. Regarding Rafaela's comment, I don't imagine that this should cause any issues with the current tutorial system, but if there is please reach out to me.

**Comment by devp4** [comment]
Sorry for the rereview. Just want to put these changes in the same PR. 

Only thing to check is if the game is running like before. Just with the expanded map.
I ran the new map with the tutorial and was able to go through all of it. 

I do notice when placing roads, you can see lines. Im not sure if there is a fix for it (other than redoing the asset) since its stitching together 4 different assets to make the road, and zooming out shows the lines. Will let Patriel know about this.

**Review by emenello — APPROVED** [review]
Everything works on my end, and this actually fixed the screen bouncing for me! Good job Dev!

**Review by carlsuarez — APPROVED** [review]
Everything works on my end. Good job!

**Review by rafaela-eacf — APPROVED** [review]
Lgtm! Good job Dev :)

**Pull request merged**
