### PR TITLE
Save/Load/Continue Features

### PR DESCRIPTION
**Pull request by devp4**
Hello! Here is the PR for the Save/Load/Continue features. Branched of Logan to test multi-tiles.

Changes include ability to:
- Save current game data to json
- Load the saved json file back
- Continue the most recently loaded game 

It DOES NOT include saving the tutorial/NPC system. For example, entering Shop dialogue will not work properly when switching between loads. Patriel said this is fine and will be worked on later. 

I think I tested everything and its working, but I also don't know the complete ins and outs of the game yet, so if something looks wrong, please let me know.

### CODE REVIEW

**Review by acher0nparth — CHANGES_REQUESTED** [review]
I have some comments, some minor and some not:

I think it would be good to either remove the "Load Game" button from the menu, or otherwise prevent it from doing anything. Currently it just opens up a file browser to the game files, and if we are only supporting continuing the most recently played game then the button isn't necessary anyway. 

The same thing is true of the "save" button that can be found on the pause menu. If we are only allowing the most recently played game to be loaded, the quit button should be replaced by "save and quit", and clicking that button should automatically save the player's game into the `continue.json` file. 

When I click "continue" from the home menu, it starts a new game. Is this intentional? This isn't an issue per se, I'm just curious. 

Also, it seems like this branch is based off of Logan's branch with the new assets, rather than a branch of main. In the future please make your branches based off of main. Unless we discussed doing this, which could make sense because of the asset stuff, in which case disregard this comment. Either way, we need to make sure to merge Logan's branch in first, then merge main back into this branch to make sure there will be no conflicts or anything. 

I'm not sure if this is the correct way to use the system, but when I clicked "save", and then overwrote `continue.json` to store the map data, when I tried to click the "continue" button on a subsequent playthrough the game crashed with error `invalid get index 'previous_map_path' (on base: 'Dictionary')`. I think this problem should be fixed if the changes to the buttons described above are implemented so the user doesn't have the opportunity to mess anything up.

**Comment by devp4** [comment]
Hey Blake, thanks for the comments! I realized I should've explained the system better (my bullet points were worded poorly). 

You can load ANY of the previous saved game files, not just the most recent one. The continue button will load the most recently played game.

For example, you can start a new game, play it, and save it. To save it, you just give it a name and hit save. You can save it anywhere, but the "saves" folder makes most sense (kind of like saving a Word doc). Then in the main menu (or in game) when you click Load Game, you can open the file you just saved to load it. You can also open any other games you have saved.

The continue file is not meant to be touched. It just contains the path to the most recently loaded game so it knows where to find the file when you hit continue.

The continue button starting a new game when they first click it was intentional. However, I think it would actually be better if I disable it until they start a game. 

As for the branch, this time I needed Logans multi-tile feature see if saving/loading works with that feature. Will definitely branch from main in future. 

I hope that makes more sense but please let me know if there are other questions!

**Comment by acher0nparth** [comment]
Thanks for the clarifications, makes more sense now. I did some more testing and have some issues and thoughts: 

This PR does not work with the packaging stuff I developed earlier this semester; I assume because you changed where the save files load from/save to. You should try it yourself (follow the documentation I wrote) and see what happens: the game starts, but no data loads in for the map. The packaging directory is currently structured so there is only the SimCoast exe and a directory called "saves" where all the save files are stored, which is currently just containing `default.json`. Feel free to change that structure as you need to make your feature work, but the bottom line is that this Save/Load functionality _must_ work when the game is packaged since it's a core playability feature.

On a related point, I think you should change where the save and load dialogs open to. Leaving it as opening to the middle of the code-base is kind of asking for things to start getting really messy as people create saves during testing and then don't delete them, and there are already a lot of random-ish files sitting in the top-level directory. Presumably this would also allow for easier integration with packaging, since there will only be one directory where the player can save their game (as of now, this can of course change at your discretion). Hopefully these should be relatively quick fixes. Let me know if you have any questions.

**Comment by devp4** [comment]
Changes:

The continue button is disabled until a map has been played. 

I changed the location saving is done. Godot has two file systems. res:// and user://. Res:// is is basically the source code location but its READ only, so I can't write user data to that path. User:// is where Godot stores persistent data and is READ/WRITE. Apparently, a lot of games store user data here, so Ill store user maps there since its the best practice and keeps things organized. This can change if needed.

File dialogs will open directly to saves folder. To view the data manually, it is located at AppData/Roaming/app_userdata/SimCoast

The default map is packaged with the game. Just one change when exporting, simply add *.json to the filters under Project -> Export -> Resources.
image

Let me know if something doesn't work / have questions!

**Comment by Lchenicek** [comment]
Wow this is so cool! I love that we're finally working on this feature. I was not able to find any issues with the buttons or saving and loading, and it looks like there's no merge conflicts with the updated main branch either. I didn't mess with the exporting stuff since Blake knows a lot more about that but I love everything else!

**Review by Lchenicek — APPROVED** [review]
Forgot to actually approve it lol

**Review by lolxela — APPROVED** [review]
Everything worked like I expected it to and the changes you made look good to me. I'm approving but I guess this merge will be pending Logan's PR?

**Review by rafaela-eacf — APPROVED** [review]
Looks good! Aside from the shop dialogue, it seems that everything is saved/loaded correctly and you already explained the dialogue thing, so it's ok. Great work!

**Review by acher0nparth — CHANGES_REQUESTED** [review]
I did a re-review of this PR, I think it looks a LOT better after the changes you made. I do have some comments, only two of which are really serious. 
* I like the changes to the file location, I think it's more intuitive and also much more in-line with industry practice. It also has the nice side effect of preserving my saves that I make in editor so I can use them when the game is exported also.  
* I did notice that on export, the game also exports the last played file from `continue.json`, so I'm going to add language to the documentation specifying to delete that file before export. Is deleting it safe, or should we just blank out the contents?
* Other than the continue thing, the game seems to work GREAT when exported. I love love love that we can just export a single EXE now and not have to worry about a directory structure. Really awesome. 
* [serious] I think that the quit button should open a popup to confirm whether the player wishes to quit without saving, and give then an option to save their files. I feel like this is a feature of a lot of programs nowadays, so users may expect that behavior. 
* [serious] I encountered a strange bug when I saved and then clicked continue on the pause menu. The game board zoomed out, picture below: 
image
I watched this happen as I typed in a filename to save my first save, specifically named `test_save_1`. The game zoomed out each time I used the underscore key, but only up to twice. Further underscores after the second one had no effect, probably due to a limit on our camera's zoom out ability. If you save the file anyway and then try to reload it without quitting, the game stays zoomed out. If you save the file, quit out, and then reload the file, the game looks normal. Super weird! At first I couldn't figure out what the issue was, but once I figured out the underscore thing I could reliably reproduce it. 
* When I tried to verify the filepath manually, I couldn't find the one you specified. I think you missed a directory; the filepath I found for the saves is: `AppData\Roaming\Godot\app_userdata\SimCoast\saves`. I am not able to confirm the location on Mac or Linux. 

Overall, I think you're doing some really solid work here. Good job!

**Comment by devp4** [comment]
Changes: 

- The bug was the camera zooming in and out as you mentioned. I disabled the zoom in/out function if the file dialog is open. 
- Added a popup that reminds the user before they quit. I tried creating a save button in the quit popup that opens the save dialog, but I could not get it to work properly (UI is not fun haha). If that is a must, I can try again.

As for the continue file, you can delete the file or the entire folder and it should work. Blanking out the contents will not work. 

Miswording on my part. SimCoast **content** is located at `AppData\Roaming\Godot\app_userdata\SimCoast\`, since it contains all user content. But yes, saves alone is located at `AppData\Roaming\Godot\app_userdata\SimCoast\saves`.

Here are the locations for each OS:
Windows: %APPDATA%\Godot\app_userdata\\[project_name]
macOS: ~/Library/Application Support/Godot/app_userdata/[project_name]
Linux: ~/.local/share/godot/app_userdata/[project_name]
 
Let me know if something doesn't work / have questions!

**Review by acher0nparth — APPROVED** [review]
* I think the reminder before quitting is perfectly fine, it certainly accomplishes the task of letting the user know that they need to save first. 
* I could not reproduce the underscore bug anymore, so I think your fix works!

PR Approved. This is some great work, nice job.

**Review by emenello — APPROVED** [review]
Everything on my end works perfectly. This is really cool! I held off on approving it because I was able to recreate the bug before, but the underscore thing is fixed now so all good!

**Pull request merged**
