### PR TITLE
Achievement Menu, Pause Menu, Achievement Popups

### PR DESCRIPTION
**Pull request by Lchenicek**
In this PR I implemented a pause menu that can be toggled by pressing escape. This way the users can pause the game if they want and we can also add some options here or access other menus. I also implemented a display menu for the achievements that is accessed through the pause menu. The functionality is good but I'm not the best at making it look nice so if you want to change the menu or the icons, they can be changed from AchievementMenu.tscn or Achievement.tscn respectively. Finally I just changed the achievement popup to be a fade in animation and I also worked on implementing a queue system so that the animations aren't all playing at the same time.

### CODE REVIEW

**Review by lolxela — COMMENTED** [review]
I love the achievement menu!! I noticed that you can still toggle the pause/play button but it won't open the pause menu, is that something you plan on adding/changing?

**Comment by Lchenicek** [comment]
I actually hadn't thought about that. I had been thinking of them as two separate things, like ones for pausing to open different menus/save whereas the other is if you want to stop time and plan your city. There's no reason I can't combine them though so if you guys think I should, let me know!

**Comment by lolxela** [comment]
Interesting, the only reason I really thought of them as one thing was because I was associating them both with the "pause" action, but I could see the necessity of keeping them separate for their respective purposes. Maybe when clicking pause users have the option of navigating to the pause menu? Not sure

**Review by emenello — APPROVED** [review]
The pause menu looks really good and I love the achievement menu. It definitely makes it look nicer to have all of your achievements in one place. The fade in achievements are cool too!

**Comment by acher0nparth** [comment]
> I actually hadn't thought about that. I had been thinking of them as two separate things, like ones for pausing to open different menus/save whereas the other is if you want to stop time and plan your city. There's no reason I can't combine them though so if you guys think I should, let me know!

I think that keeping them separate is fine, but I do see how it could be confusing for a player to have a 'pause button' and a 'pause menu' that aren't related. Maybe something to talk to Patriel about when we get into UI stuff?

**Review by acher0nparth — CHANGES_REQUESTED** [review]
I think this is really good work. I was able to trigger all 8 achievements with no issues, the menu looks good, and I couldn't find any problems. I am very impressed with how much more engaging this makes the game, and adding the progress bars was a really slick touch.

My only complaint--and this is quite small--is about navigating the menu itself. When I am in the 'Achievements' screen, I keep clicking `esc` as a way to exit, but that doesn't work even though it does on the pause menu itself, so I have to go click the X in the top right to exit. If you could implement that consider this PR approved.

**Comment by Lchenicek** [comment]
I went ahead and implemented both your and Alexandra's suggestions. You can now close the Achievement menu using escape and open the pause menu using the pause button. I think both those suggestions make a lot of sense, thanks!

**Review by acher0nparth — APPROVED** [review]
Changes work. Thanks!

**Review by rafaela-eacf — APPROVED** [review]
Looks great! I especially like the pop-up figures for the achievements, they are so cute! Also, all the recent modifications seem to be working for me.

**Review by lolxela — APPROVED** [review]
Nice looks good!

**Pull request merged**
