### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by lolxela**
Players can now use the dashboard! 

The dashboard has two sections: (1) a city stats side bar (left), and (2) a popup menu for badges, characters, and sensor stats (right). 

The city stats bar serves to give users more information about the numbers they can see from the start map. Users can hover over any information icon to learn more about the corresponding label. Users are also able to adjust city taxes! Each tax has a range from 0-100% for the user, but this range only allows them to adjust a fraction of the tax value in Econ.gd. Please check dashboard.gd to see the real ranges, and feel free to check my math!

The menu on the right allows users to view their unlocked badges, field professionals, and sensor stats (TBD). You can hover over the plus buttons on the right to preview each panel, and click to expand/minimize. Currently each test character is set to "locked", but you can test functionality of unlocked characters by going to CharacterCard.gd and editing line 17, "charUnlocked = unlocked" to "charUnlocked = true".

Eddie also contributed to this commit by implementing the character cards and connecting them to NPCs.
Logan contributed by implementing badges, which were made on the badges branch and merged into dashboard.

### CODE REVIEW

**Comment by Lchenicek** [comment]
Hey Alexandria,

You're additions look really good. I love the layout of the dashboard and I'm looking forward to seeing it integrated with the sensor data. The only thing I noticed when reviewing the PR is that it looks like the fonts in a couple places were changed. I noticed it on the achievement menu, shop menu and toolbar. I was just wondering if these were intentional? I included some comparisons with main as well.

Your branch:
image
image

Main:
image
image

**Review by acher0nparth — COMMENTED** [review]
Hey! This PR looks great. I didn't find any issues other than the stuff @Lchenicek mentioned in his earlier comment. I also tested this with the export steps and the game exports fine with the dashboard assets added in. Once the font thing is fixed I'm happy to approve.

**Comment by lolxela** [comment]
Definitely not intentional! Not sure how that happened but I’ll fix it ASAP

**Review by devp4 — APPROVED** [review]
Didn't run into any issues on my end and the dashboard looks great!

**Comment by lolxela** [comment]
Should be fixed!

**Review by Lchenicek — APPROVED** [review]
Changes look good! Thanks for fixing that

**Review by emenello — APPROVED** [review]
The changes look great! Just a note on unlocking characters. The character cards are currently connected to the NPC organizer so another way to test unlocking them would be to set the value of unlocked to true on the NPC object would also work! (or call unlockNPC anywhere in the code)

**Comment by lolxela** [comment]
Cool I'll remember that for next time

**Review by rafaela-eacf — APPROVED** [review]
Looks great! Everything works and I couldn't find any bugs.

**Review by acher0nparth — APPROVED** [review]
Thanks for fixing the font thing! All good then.

**Pull request merged**
