### PR TITLE
Bug fixes!

### PR DESCRIPTION
**Pull request by acher0nparth**
This PR fixes some of the bugs that are on the Trello board, namely:
-  Population not deleted when overwriting zoned residential tile
- Recalculate power on power plant deletion
- population not properly moving out

I also did some refactoring:
- removed the variable `TOTAL_POPULATION` from `UpdatePopulation.gd` as it was not really useful and added an annoying amount of steps. 
- made the `remove_people` and `add_people` functions better because they now directly remove people (seems like that should have always been the case, blame past me!)
- made the `remove_building` function remove buildings AND remove population now, so you no longer need to do that manually. 
- Fixed the clear tile function so it clears the tile in a better way that's more thorough and useful.

### CODE REVIEW

**Comment by acher0nparth** [comment]
## UPDATE

I have fixed the bug indicated by Rafaela in our meeting, power should reconnect if a power plant OR a road is cleared, not just power plants. Good catch! 

I have also resolved the merge conflict between this branch and main by moving the Announcer code from Logan for removing buildings by moving it in to the `remove_building` function instead of in `clear_tile`. This should make it easier to notify the announcer anytime any building is removed anywhere in the code, not just in `clear_tile`.

**Review by rafaela-eacf — DISMISSED** [review]
Hey Blake! The population is properly being deleted when overwritten and the power is leaving when the power plant is deleted. 
I'm still having some issues with the last bug though. The changes you made fixed that scenario we talked about, but now I tried creating two rows of houses. When I remove a horizontal road, everything goes according to plan and the correct houses lose power. However, if I remove a vertical road, the houses still get power. Only when I add a new road after that or remove a horizontal road, it gets fixed. Basically, it takes one more road check somehow for vertical roads, if that makes sense. I attached a picture of the simulation I tried so you can recreate it. Thanks!
simcoast_bug

**Comment by acher0nparth** [comment]
## UPDATE 2

Thank you to Rafaela for pointing out this bug, it was very insidious. Someone previously had misused the `data` member variable of each tile to store road connections. I fixed this by adding a variable `connections` for each tile that functions the same way as data. This allowed me to make a smooth replacement with minimal code modifications. I think the implementation is a little clumsy but at this point I'm not suuuuuper interested in going back to clean it up. 

As always, take this one for a spin and see if you can find anything else!

**Review by rafaela-eacf — APPROVED** [review]
It's fixed for me! Thank you Blake for taking the time to go back and change this twice now.

**Review by lolxela — APPROVED** [review]
Everything worked for me

**Review by Lchenicek — APPROVED** [review]
The previously mentioned bugs seemed to be fixed and I can't find any new ones. Looks really good!

**Comment by Lchenicek** [comment]
Oh wait sorry, I decided to try something and I did end up finding a small bug. It looks like you moved the announcer for when tiles get deleted, does it need to be in the new spot or does the old one still work. Because on main, if you overwrite a tile with another tile, you still need to have 5 total buildings to get an achievement. Whereas, with the other implementation, it only check if we delete the tile ourselves, not if it's overwritten. So if you overwrite a commercial area with another tile, it awards the achievement even if you only have 4 of the tiles. Here's a quick demo of what I'm talking about

https://github.com/cacticouncil/simcoast/assets/71045676/91a1ce4c-fe1d-428d-bbf9-cc10eae6493d

**Comment by Lchenicek** [comment]
The bug I found looks to be fixed! Everything looks great now :)

**Review by emenello — APPROVED** [review]
Everything worked for me!

**Pull request merged**
