### PR TITLE
Road Damage

### PR DESCRIPTION
**Pull request by lolxela**
Road damage is now impacted by city wear and tear.

Sorry for getting this out so late it, fell under my radar this week.

City.gd:
Added **calculate_wear_and_tear()** function which is called monthly in updateDate. This function calculates wear and tear on road tiles while taking into account the population of surrounding tiles. The function checks surrounding zoned tiles for current population (data[2]). A variable chanceOfDamage is increased some amount depending on that population for each surrounding tile. For public works zones, a flat rate is added to chanceOfDamage since they do not hold population (if there is a better, more intuitive measurement for this that I missed please let me know!) A random number is created to determine if wear and tear has happened that month. If so, another random number determines the extent of damage and updates a new tile property wearAndTear with that damage.

Edited **calculate_damage()** function to include road/bridge tiles. Water height now effects road tile damage rather than just wiping a road out. The function also checks if wearAndTear has been modified and calls set_damage to apply damage to road tiles.

Tile.gd:
Added tile property for wearAndTear as well as a bool to indicate if its been updated and a getter function.
Edited **set_damage()** function so that if damage exceeds 100% the road tile is removed.

HUD.gd:
Added tile damage to bottom bar when hovering over road tiles.

Let me know what you think!

### CODE REVIEW

**Review by acher0nparth — CHANGES_REQUESTED** [review]
I'm going to "request changes", but if you don't want to make these changes or don't think they're needed then just say so and I'll give it the approval. I didn't notice any bugs or any major issues, and overall I think this is pretty solid work. 
* I think some public works tiles should still be affected by population, maybe just in a larger or smaller radius depending on the tile. Parks for example will get used (and therefore degrade) more if there are more people around to go to the park. I think the same thing could apply to museums and schools, but not necessarily hospitals, police stations, and fire stations, since the only people in there are people with jobs in the building. I think it _could_ apply to those as well, but I'm not sure. You could check the population in adjacent tiles (or even tiles further away) to calculate wear and tear. 
* We still don't have a way to remove tile damage other than removing and replacing the tile. We used to have this functionality but it got deleted when we shifted the UI to the new model. I'm not sure if we want to add it to this PR, but we are coming up on the point where it won't be an option anymore. 
* Thanks for fixing my if statement in `calculate_damage`, it was silly of me to leave the `&& changeInWaterHeight > 0` in every lower level statement when I could've just added it to the top-level one. 
* Forgive me if we've addressed this before, but is there a cutoff point where utilities stop flowing through a road? I know it stops when the road hits 100% damage and gets cleared off, but what about 50% or 75%? Not sure if we really need this feature, but it does bear discussing (which is why I think we may have talked about it before, but I just forgot).
* I think you should work with Logan to make some sprites for damaged roads. As I recall, we used to have damaged buildings change color as a visual indicator, since otherwise the player has to individually hover over every tile. I'm not sure if that's still a thing with the new assets, but it definitely should be! I noticed while playing that I had a hard time determining which roads were wearing down and which weren't unless I kept moving my mouse to check all the roads constantly.

**Comment by lolxela** [comment]
Thanks for reviewing Blake! That's a good idea about the public works tiles that I will definitely implement. Things like hospitals could also be city population dependent since 2 hospitals would get less traffic than 1 hospital, but it seems a little in the weeds for this game so I'll stick to radius for some public works. I did think about how damaged tiles couldn't be fixed but just sounded like it needed some communication with UI design; I'll bring it up during todays meeting. I asked Patriel a few meetings ago about how damage level should impact util functionality and she said she would get back to me so I'll also bring that up again, as well as giving them a sprite based on damage which sounds fun!

**Review by Lchenicek — APPROVED** [review]
Hey Alexandra, I wasn't able to find any bugs on my end! I do agree with Blake that I think some indicator of the tiles being damaged would be appropriate but as we already discussed, I think a new sprite would be overkill for now. All I was really doing was getting the system set up to import some new assets in but I think they're all going to be redone at some point so I think something like adding a tint to the tiles would be more than enough and easy to do in Godot. But I'll go ahead and approve for now!

**Review by rafaela-eacf — APPROVED** [review]
Looks good to me! I like that we can see the damage in the HUD, and as previously mentioned it would be nice to add a visual for the damaged tiles if you can.

**Comment by lolxela** [comment]
A few changes, roads can be repaired for a smaller cost on a left click while on road tool. Cost depends on extent of damage. For now road tiles get a red shade when they're damaged and the shade darkens for higher damage. Some public works are dependent on surrounding tiles although I'm not too sure about the computational time it takes. I didn't want to make it too complicated with multiple public works zones together so I limited their impact to only be based on populations of commercial and residential zones (not other public works) within their radius.

**Comment by lolxela** [comment]
Added confirmation popup for repairing the roads

**Review by acher0nparth — APPROVED** [review]
Looks good! The roads definitely are damaged more around population centers, which is awesome. I like that the costs scale with damage too, more things for the player to spend cash on. 

I did notice that the commercial population move-out bug is present on this branch, which I thought was fixed recently. I'm assuming that the culprit is that this branch has been out for a while and hasn't pulled from main. Could you verify that the bug is not present after your merge? Other than that, approved!

**Comment by lolxela** [comment]
Hm I actually merged main in to my branch 2 days ago and as far as I know there haven’t been any PRs merged between now and then. I’m also not super familiar with the bug, what should I be looking out for?

**Comment by acher0nparth** [comment]
Essentially, if the game runs for a bit the commercial population sometimes just moves out. If you can get the game running for 20 minutes or so and don’t see it happen after doing that a few times then you’re probably fine. Just build up a nice city and let it run for a while and then come back to check on it.

Blake Thacker
________________________________

**Comment by Lchenicek** [comment]
Hey Blake, I don't think that fix is on main quite yet. I believe it was on my branch that I was just going to add with my next PR since it changed so little code.

**Comment by acher0nparth** [comment]
> Hey Blake, I don't think that fix is on main quite yet. I believe it was on my branch that I was just going to add with my next PR since it changed so little code.

I definitely forgot about that, thanks!

**Comment by devp4** [comment]
Looks great! I wasn't able to find any bugs or issues.

**Review by devp4 — APPROVED** [review]

**Review by emenello — APPROVED** [review]
Looks good to me! I wasn't able to find any bugs either. Great job!

**Pull request merged**
